project:
  type: website
  output-dir: docs

website:
  title: "quarto4rubydata"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - ipynb2pdforword.qmd
      - crossref4figtbl.qmd
      - ipynb2website.qmd

format:
  html:
    theme: cosmo
    css: style.css
    toc: true
